# Generated by Django 4.1.7 on 2023-08-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setreminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('sms', models.IntegerField()),
            ],
        ),
    ]
